version: "3.8"

services:
  database:
    image: postgres:15
    container_name: flagit_db
    restart: always
    environment:
      POSTGRES_USER: flag_user
      POSTGRES_PASSWORD: flag_password
      POSTGRES_DB: flagit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flagit_backend
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://flag_user:flag_password@database:5432/flagit_db?schema=public"
      JWT_SECRET: "your-secret-key"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]

volumes:
  postgres_data:
